"""Builds src/assets_gen.js from every art script in this folder.

    python tools/build_assets.py
"""
import json, os
import numpy as np
from PIL import Image
from pixlib import Atlas, to_data_uri
import build_sprites, heroine, shadow, tiles

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "src", "assets_gen.js")


def crop(arr, ax, ay):
    a = arr[..., 3] > 0
    if not a.any():
        return arr[:1, :1], 0, 0
    ys, xs = np.nonzero(a)
    x0, y0, x1, y1 = xs.min(), ys.min(), xs.max() + 1, ys.max() + 1
    return arr[y0:y1, x0:x1], int(ax - x0), int(ay - y0)


def pack(items, width=512):
    at = Atlas(width)
    for name, (arr, ax, ay) in items.items():
        c, cx, cy = crop(arr, ax, ay)
        at.add(name, c, cx, cy)
    im, rects = at.build()
    return im, rects


def main():
    data = {}
    # hero ---------------------------------------------------------------
    hero = build_sprites.hero_items()
    keep = {}
    for i in range(15):
        keep[f"walk{i}"] = hero[f"walk{i}"]
    for i in range(21):
        keep[f"run{i}"] = hero[f"run{i}"]
    for i in range(25):
        keep[f"jump{i}"] = hero[f"jump{i}"]
    keep["front"] = hero["front"]
    for k, v in hero.items():
        if k.startswith("atk"):
            keep[k] = v
    im, rects = pack(keep, 512)
    data["hero"] = {"src": to_data_uri(im), "f": rects, "tip": build_sprites.ATTACK_TIPS}
    # heroine --------------------------------------------------------------
    F = heroine.frames()
    F["front"] = heroine.front()
    items = {}
    for k, v in F.items():
        ax, ay = heroine.ANCHORS.get(k, (heroine.AX, heroine.AY))
        if k == "front":
            ax, ay = v.shape[1] // 2, v.shape[0] - 1
        items[k] = (v, ax, ay)
    im2, rects = pack(items, 256)
    data["heroine"] = {"src": to_data_uri(im2), "f": rects}
    # shadow ---------------------------------------------------------------
    S, carry = shadow.frames()
    items = {k: (v, shadow.AX, shadow.AY) for k, v in S.items()}
    im3, rects = pack(items, 256)
    data["shadow"] = {"src": to_data_uri(im3), "f": rects,
                      "carry": {k: [v[0] - shadow.AX, v[1] - shadow.AY] for k, v in carry.items()}}
    # tiles / props ----------------------------------------------------------
    T = tiles.all_items()
    at = Atlas(256)
    for k, v in T.items():
        at.add(k, v, 0, 0)
    im4, rects = at.build()
    data["tiles"] = {"src": to_data_uri(im4), "f": rects}
    data["bgfar"] = {"src": to_data_uri(Image.fromarray(tiles.bg_far(), "RGBA"))}
    data["bgmid"] = {"src": to_data_uri(Image.fromarray(tiles.bg_mid(), "RGBA"))}

    with open(OUT, "w", encoding="utf-8") as f:
        f.write("// generated by tools/build_assets.py - do not edit\n")
        f.write("window.ASSETS = ")
        json.dump(data, f, separators=(",", ":"))
        f.write(";\n")
    print("wrote", OUT, os.path.getsize(OUT) // 1024, "KB")
    for n, im_ in (("hero", im), ("heroine", im2), ("shadow", im3), ("tiles", im4)):
        print(" ", n, im_.size)


if __name__ == "__main__":
    main()
